name: flutter_project_template
description: Flutter Template Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  # [All]
  # 기본 플러터 개발 도구
  flutter:
    sdk: flutter

  # apple 디자인 아이콘
  cupertino_icons: ^1.0.5

  # Semaphore 사용
  sync: ^0.3.0

  # 상태 관리 bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # 스크린 포커스 감지
  focus_detector_v2: ^3.1.0+1

  # Web Url 개선
  url_strategy: ^0.2.0

  # Router 개선
  go_router: ^10.1.0

  # Web SEO 개선
  seo_renderer: ^0.6.0

  # 앱 정보 가져오기
  package_info_plus: ^4.1.0

  # 디바이스 정보 가져오기
  device_info_plus: ^9.0.3

  # SharedPreferences
  shared_preferences: ^2.2.0

  # 네트워크 리퀘스트
  http: ^1.1.0

  # 네트워크 리퀘스트 개선
  dio: ^5.3.2

  # 웹 브라우저 열기
  url_launcher: ^6.1.12

  # Toast
  flutter_styled_toast: ^2.1.3

  # 파일 선택
  # pickFiles (all), getDirectoryPath (web 제외), saveFile (PC), clearTemporaryFiles (Mobile)
  file_picker: ^5.3.3

  # DateTime
  intl: ^0.18.1

  # Gif 재생
  flutter_gif: ^0.0.4

  # Dio Logger
  pretty_dio_logger: ^1.3.1

  # 암호화
  encrypt: ^5.0.1

  # JWT 생성
  dart_jsonwebtoken: ^2.10.0

  ####
  # [Mobile]
  # 앱 스토어 이동
  store_redirect: ^2.0.1

  # 모바일 권한 처리
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  # 리소스 파일 설정
  assets:
    # 이미지 파일
    - lib/assets/images/

  # 폰트 리소스 설정
  # weight :
  # 100 : thin, 200 : extraLight, 300 : light, 400 : regular, 500 : medium, 600 : semiBold, 700 : bold, 800 : extraBold, 900 : heavy
  fonts:
    - family: NanumGothic
      fonts:
        - asset: lib/assets/fonts/NanumGothic/NanumGothicLight.ttf
          weight: 300
        - asset: lib/assets/fonts/NanumGothic/NanumGothic.ttf
          weight: 400
        - asset: lib/assets/fonts/NanumGothic/NanumGothicBold.ttf
          weight: 700
        - asset: lib/assets/fonts/NanumGothic/NanumGothicExtraBold.ttf
          weight: 800

    - family: NanumMyeongjo
      fonts:
        - asset: lib/assets/fonts/NanumMyeongjo/NanumMyeongjo.ttf
          weight: 400
        - asset: lib/assets/fonts/NanumMyeongjo/NanumMyeongjoBold.ttf
          weight: 700
        - asset: lib/assets/fonts/NanumMyeongjo/NanumMyeongjoExtraBold.ttf
          weight: 800

    - family: NanumSquare
      fonts:
        - asset: lib/assets/fonts/NanumSquare/NanumSquareL.ttf
          weight: 300
        - asset: lib/assets/fonts/NanumSquare/NanumSquareR.ttf
          weight: 400
        - asset: lib/assets/fonts/NanumSquare/NanumSquareB.ttf
          weight: 700
        - asset: lib/assets/fonts/NanumSquare/NanumSquareEB.ttf
          weight: 800

    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Inter/Inter-Black.ttf
          weight: 900